home/urls.py
from django.conf.urls import url
from  home.views import HomeView,Home
from home import views
app_name='home'
urlpatterns=[
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends, name='change_friends')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from mysite import views as login_redirect_view
from django.conf.urls import  url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',login_redirect_view.login_redirect,name='login_redirect'),
    path('account/', include('polls.urls',namespace='account')),
    path('UserTest/', include('UserTest.urls')),
    url(r'^home/', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
#

polls/urls.py
from django.urls import path
from django.conf.urls import  url
from django.contrib.auth.views import (
    login,logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
)
from . import views

app_name='account'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^$',views.Home,name='home'),
    url(r'^login/$',login,{'template_name':'account/login.html'},name='login'),
    url(r'^logout/$',logout,{'template_name':'account/logout.html'},name='logout'),
    url(r'^register_user/$',views.register_user,name='register_user'),
    url(r'^view_profile/$',views.View_profile,name='view_profile'),
    url(r'^view_profile/(?P<pk>\d+)$',views.View_profile,name='view_profile_with_pk'),
    url(r'^edit_profile/$',views.Edit_Profile,name='edit_profile'),
    url(r'^password_change/$',views.Change_password,name='password_change'),

    url(r'^password_reset/$',password_reset,{'template_name':'account/password_reset.html',
                                             'post_reset_redirect':'account:password_reset_done',
                                             'email_template_name':'account/email_template_name.html'},
                                              name='password_reset'),

    url(r'^password_reset/done/$',password_reset_done,{'template_name':'account/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,{'template_name':'account/password_reset_confirm.html',
                                'post_reset_redirect':'account:password_reset_complete'},name='password_reset_confirm'),

    url(r'^password_reset/complete/$',password_reset_complete,{'template_name':'account/password_reset_complete.html'},
        name='password_reset_complete'),


    path('cart/', views.Cart, name='cart'),
    path('product/', views.Product, name='product'),
    path('category/', views.Category, name='category'),

]

home/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    post = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post


class Friend(models.Model):
    user = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True,on_delete=models.CASCADE)


    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

home/forms.py
from django import forms
from home.models import Post


class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            "class": 'form-control',
            'placeholder':'Write your post',

               }
    ))

    class Meta:
        model = Post
        fields = ('post',)

home/views.py
from django.views.generic import TemplateView
from django.shortcuts import HttpResponse, render, redirect
from home.forms import HomeForm
from home.models import Post, Friend
from django.contrib.auth.models import User


class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request, *args, **kwargs):
        form = HomeForm()
        posts = Post.objects.all().order_by('-updated')
        user = User.objects.exclude(id=request.user.id)
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
        args = {
            'form': form,
            'posts': posts,
            'users': user,
            'friends':friends,
        }
        return render(request, self.template_name, args)

    def post(self, request):
        print("Namatullah")
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            text = form.cleaned_data['post']
            form = HomeForm()
        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)


def Home(request):
    return HttpResponse("Namatullah wahidi")


def change_friends(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user, friend)
    return redirect('home:home')

home/templates/home/home.html
{% extends 'home.html' %}
{% block MainContent %}

     <div class="container">
        <div class="row">
          <div class="col-md-8">
                <form method="post">
                    {% csrf_token %}
                    <h3>Post</h3>
                    {{ form.post}}<br>
                    <button class="btn btn-outline-success" type="submit" >Submit</button>
                </form>
                <P style="padding-left:40px">{{ text }}</P>
                {% for post in posts %}

                    <h1>{{ post.post }}</h1>
                    <p>Posted By:{{ post.user.get_full_name }} updated on {{ post.updated }} and created on{{ post.created }}</p>

                {% endfor %}
         </div>
         <div class="col-md-4" style="margin-top: 40px">
             <h1>Other people</h1>
              {% for user in users %}
                    <h3><a href="{% url 'account:view_profile_with_pk' pk=user.pk %}">{{ user.username }}</a></h3>
              {% endfor %}

          <h2>Friends</h2>
        {% for friend in friends %}
            <a href="{% url 'accounts:view_profile_with_pk' pk=friend.pk %}">
                <h3>{{ friend.username }}</h3>
            </a>
            <a href="{% url 'home:change_friends' operation='remove' pk=friend.pk %}">
            <button type="button" class="btn btn-default">Remove Friend</button>
            </a>
        {% endfor %}
         </div>
        </div>
    </div>

{% endblock %}