home/urls.py
from django.conf.urls import url
from  home.views import HomeView,Home
from home import views
app_name='home'
urlpatterns=[
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends, name='change_friends')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from mysite import views as login_redirect_view
from django.conf.urls import  url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',login_redirect_view.login_redirect,name='login_redirect'),
    path('account/', include('polls.urls',namespace='account')),
    path('UserTest/', include('UserTest.urls')),
    url(r'^home/', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
#

polls/urls.py
from django.urls import path
from django.conf.urls import  url
from django.contrib.auth.views import (
    login,logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
)
from . import views

app_name='account'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^$',views.Home,name='home'),
    url(r'^login/$',login,{'template_name':'account/login.html'},name='login'),
    url(r'^logout/$',logout,{'template_name':'account/logout.html'},name='logout'),
    url(r'^register_user/$',views.register_user,name='register_user'),
    url(r'^view_profile/$',views.View_profile,name='view_profile'),
    url(r'^view_profile/(?P<pk>\d+)$',views.View_profile,name='view_profile_with_pk'),
    url(r'^edit_profile/$',views.Edit_Profile,name='edit_profile'),
    url(r'^password_change/$',views.Change_password,name='password_change'),

    url(r'^password_reset/$',password_reset,{'template_name':'account/password_reset.html',
                                             'post_reset_redirect':'account:password_reset_done',
                                             'email_template_name':'account/email_template_name.html'},
                                              name='password_reset'),

    url(r'^password_reset/done/$',password_reset_done,{'template_name':'account/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,{'template_name':'account/password_reset_confirm.html',
                                'post_reset_redirect':'account:password_reset_complete'},name='password_reset_confirm'),

    url(r'^password_reset/complete/$',password_reset_complete,{'template_name':'account/password_reset_complete.html'},
        name='password_reset_complete'),


    path('cart/', views.Cart, name='cart'),
    path('product/', views.Product, name='product'),
    path('category/', views.Category, name='category'),

]

home/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    post = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post


class Friend(models.Model):
    user = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True,on_delete=models.CASCADE)


    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)

polls/models.py
from django.db import models
from django.contrib.auth.models import User

from django_resized import ResizedImageField



class Information(models.Model):
    name = models.CharField(max_length=42)
    email = models.EmailField(max_length=75)
    website = models.URLField(max_length=200, null=True, blank=True)
    content = models.TextField()


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class ProfileManager(models.Manager):
    def get_queryset(self):
        return super(ProfileManager, self).get_queryset().filter(city="Kandahar City")


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image_original = models.ImageField(upload_to=user_directory_path,blank=True)
    image = ResizedImageField(size=[100, 100], crop=['middle', 'center'], upload_to=user_directory_path,
                              blank=True, null=True)



    # if we want to get ProfileManger we can call this object for example we can call only kandar city
    # kandar=ProfileManager()

    def __str__(self):
        return self.user.username


# make trigger for database
from django.db.models.signals import post_save


def create_profile(sender, **kewargs):
    if kewargs['created']:
        user_profile = Profile.objects.create(user=kewargs['instance'])


post_save.connect(create_profile, sender=User)

home/forms.py
from django import forms
from home.models import Post


class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            "class": 'form-control',
            'placeholder':'Write your post',

               }
    ))

    class Meta:
        model = Post
        fields = ('post',)

polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm


class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)

    class Meta:
        model=User
        fields={
            'username',
            'first_name',
            'password1',
            'password2',
            'last_name',
            'email',
        }
    def save(self,commit=True):
        user=super(RegistrationForm,self).save(commit=False)
        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']
        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

home/views.py
from django.views.generic import TemplateView
from django.shortcuts import HttpResponse, render, redirect
from home.forms import HomeForm
from home.models import Post, Friend
from django.contrib.auth.models import User


class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request, *args, **kwargs):
        form = HomeForm()
        posts = Post.objects.all().order_by('-updated')
        user = User.objects.exclude(id=request.user.id)
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
        args = {
            'form': form,
            'posts': posts,
            'users': user,
            'friends':friends,
        }
        return render(request, self.template_name, args)

    def post(self, request):
        print("Namatullah")
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            text = form.cleaned_data['post']
            form = HomeForm()
        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)


def Home(request):
    return HttpResponse("Namatullah wahidi")


def change_friends(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user, friend)
    return redirect('home:home')

polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import matplotlib.pyplot as plot
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from polls.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, "base.html")



def Home(request):
    return render(request, "home.html")


# def register_user(request):
#     if request.method=="POST":
#         print("method is post")
#         form=UserCreationForm(request.POST)
#
#         if form.is_valid():
#             print("form is valid")
#             form .save()
#             return  redirect('/account/')
#     else:
#         print("form is invalid")
#         form=UserCreationForm()
#         args={'form':form}
#         return render(request,'account/reg_form.html',args)

# we can use for custom user

def register_user(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            args = {'user': request.user}
            return redirect('account:home')
            # return render(request, 'home.html', args)
    else:
        form = RegistrationForm()
    args = {'form': form}
    return render(request, 'account/reg_form.html', args)



def View_profile(request,pk=None):
    if pk:
        user=User.objects.get(pk=pk)
    else:
        user=request.user
    args = {'user': user}
    return render(request, 'account/profile.html', args)


@login_required
def Edit_Profile(request):
    if request.method == "POST":
        form = EditProfileForm(data=request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('account:view_profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'account/edit_profile.html', args)


@login_required
def Change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('account:view_profile')
        else:
            return redirect('account:password_change')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'account/password_change.html', args)


def Cart(request):
    return render(request, "cart.html")


def Product(request):
    return render(request, "product.html")


def Category(request):
    return render(request, "category.html")

polls/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block MainContent %}
                <!-- Main Content -->
                <div class="row">
                    <div class="col-12 mt-3 text-center text-uppercase">
                        <h2>Shopping Cart</h2>
                    </div>
                </div>

                <main class="row">
                    <div class="col-12 bg-white py-3 mb-3">
                        <div class="row">
                            <div class="col-lg-6 col-md-8 col-sm-10 mx-auto table-responsive">
                                <form class="row">
                                    <div class="col-12">
                                        <table class="table table-striped table-hover table-sm">
                                            <thead>
                                            <tr>
                                                <th>Product</th>
                                                <th>Price</th>
                                                <th>Qty</th>
                                                <th>Amount</th>
                                                <th></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td>
                                                    <img src="{% static 'images/image-2.jpg'%}" class="img-fluid">
                                                    Optoma 4K HDR Projector
                                                </td>
                                                <td>
                                                    $1,500
                                                </td>
                                                <td>
                                                    <input type="number" min="1" value="1">
                                                </td>
                                                <td>
                                                    $1,500
                                                </td>
                                                <td>
                                                    <button class="btn btn-link text-danger"><i class="fas fa-times"></i></button>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <img src="{% static 'images/image-3.jpg'%}" class="img-fluid">
                                                    HP Envy Specter 360
                                                </td>
                                                <td>
                                                    $2,500
                                                </td>
                                                <td>
                                                    <input type="number" min="1" value="1">
                                                </td>
                                                <td>
                                                    $2,500
                                                </td>
                                                <td>
                                                    <button class="btn btn-link text-danger"><i class="fas fa-times"></i></button>
                                                </td>
                                            </tr>
                                            </tbody>
                                            <tfoot>
                                            <tr>
                                                <th colspan="3" class="text-right">Total</th>
                                                <th>$4,000</th>
                                                <th></th>
                                            </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                    <div class="col-12 text-right">
                                        <button class="btn btn-outline-secondary mr-3" type="submit">Update</button>
                                        <a href="#" class="btn btn-outline-success">Checkout</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                </main>
                <!-- Main Content -->

{% endblock %}

polls/templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block TopNav%}

          <div class="col-12 bg-dark py-2 d-md-block d-none">
              <div class="row">
                     {% if user.is_authenticated %}
                                <div class="col-auto mr-auto">
                                    <ul class="top-nav">
                                        <li>
                                            <a href="{% url 'account:view_profile' %}"><i class="fas fa-address-card mr-2"></i>View Profile</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'account:edit_profile' %}"><i class="fas fa-user-edit mr-2"></i>Edit Profile</a>
                                        </li>
                                         <li>
                                            <a href="{% url 'account:password_change' %}"><i class="fas fa-key mr-2"></i>Password Change</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'home:home' %}"><i class="fa fa-envelope mr-2"></i>Home Home</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'account:home' %}"><i class="fa fa-envelope mr-2"></i>Account Home</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-auto">
                                    <ul class="top-nav">
                                       <li>
                                            <a href="{% url 'account:logout' %}"><i class="fas fa-sign-out-alt mr-2"></i>Logout</a>
                                        </li>
                                    </ul>
                                </div>
                   {% else %}
                              <div class="col-auto mr-auto">
                                    <ul class="top-nav">
                                        <li>
                                            <a href="tel:+123-456-7890"><i class="fa fa-phone-square mr-2"></i>+123-456-7890</a>
                                        </li>
                                        <li>
                                            <a href="mailto:mail@ecom.com"><i class="fa fa-envelope mr-2"></i>mail@ecom.com</a>
                                        </li>
                                         <li>
                                            <a href="{% url 'account:password_reset' %}"><span class="fa-passwd-reset fa-stack"
                                                                                       style="font-size: 8px">
                                                  <i class="fa fa-undo fa-stack-2x"></i>
                                                  <i class="fa fa-lock fa-stack-1x"></i>
                                                </span>Passwrod Reset
                                            </a>
                                        </li>
                                    </ul>
                              </div>
                              <div class="col-auto">
                                    <ul class="top-nav">
                                        <li>
                                            <a href="{% url 'account:register_user' %}"><i class="fas fa-user-edit mr-2"></i>Register</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'account:login' %}"><i class="fas fa-sign-in-alt mr-2"></i>Login</a>
                                        </li>
                                    </ul>
                              </div>
                   {% endif %}
              </div>
          </div>
{% endblock %}
{% block Header %}
    <div class="container" style="text-align: center">
         <h1>Home Page</h1>
    </div>
{% endblock %}
{% block MainContent %}
    <div class="container">
        Home Page
    </div>
{% endblock %}
{% block footer %}
{% endblock %}

polls/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

</head>
<body>
<table>
{% for key, value in data.items %}
    <tr>
        <td> {{ key }}: </td> <td> {{ value }} </td>
    </tr>
{% endfor %}
</table>
</body>
</html>

polls/templates/menu.html
<div class="row">
      <!-- Portfolio Grid Items -->
        <div class="col-lg-2 mr-auto">
           	<div class="vertical-menu">
           		<ul class="menuBir">
                 <li class="menuIki">
                    <a class="menuUc" href="index.php?page=showData" class="nav-item nav-link active">Show Data</a>
                 </li>
                 <li class="menuIki">
                    <a class="menuUc" href="index.php?page=insertData" class="nav-item nav-link active">Insert Data</a>
                 </li>
                 <li class="menuIki">
                    <a class="menuUc" href="index.php?page=searchData" class="nav-item nav-link">Search Data</a>
                 </li>
                 <li class="menuIki">
                    <a class="menuUc" href="index.php?page=updateData" class="nav-item nav-link">Update Data</a>
                 </li>
                  <li class="menuIki">
                    <a class="menuUc" href="index.php?page=updateData1" class="nav-item nav-link">Update Data secondMehtod</a>
                 </li>
                 <li class="menuIki">
                   <a class="menuUc" href="index.php?page=deleteData" class="nav-item nav-link">Delete Data</a>
                 </li>
              </ul>
	            
	            
	            
	           

	        </div>
        </div>
   
    <div class="col-lg-10 mr-auto">

polls/templates/news.html
{% extends 'base.html' %}
{% block title %}
<title>News Page</title>
{% endblock %}
{% block menu %}
{% endblock %}
{% block body %}
<form action="{% url 'index' %}" method="post">
{% csrf_token %}

    <input type="text" name="name" placeholder="Enter your name"><br>
    <input type="email" name="email" placeholder="Enter your email"><br>
    <input type="text" name="website" placeholder="Enter your websiete address"><br>
    <input type="text" name="contact" placeholder="Enter your contact"><br>
    <input type="submit" value="Click">
</form>

{% endblock %}

polls/templates/news2.html
{% load bootstrap4 %}

{# Display a form #}

<form action="/" method="post" class="form">
    {% csrf_token %}
{#    {% bootstrap_form form %}#}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>